NUM_FEATURES = 41916
PADDED_NUM_FEATURES = 41920
HALF_INPUT_SIZE = PADDED_NUM_FEATURES
HALF_ACCUMULATOR_SIZE = 256
INPUT_SIZE = 2*HALF_INPUT_SIZE
ACCUMULATOR_SIZE = 2*HALF_ACCUMULATOR_SIZE
HIDDEN_1_SIZE = 32
HIDDEN_2_SIZE = 32
OUTPUT_SIZE = 1
MAX_ACTIVE_FEATURES = 37

WHITE = 0
BLACK = 1

INPUT_SCALE = 127.
OUTPUT_DIVISOR = 26.

WEIGHT_SCALE_ACCUMULATOR = 127.
WEIGHT_SCALE_HIDDEN_1 = 128.
WEIGHT_SCALE_HIDDEN_2 = 64.
WEIGHT_SCALE_OUT = 64.

WEIGHT_MAX_HIDDEN_1    = INPUT_SCALE / WEIGHT_SCALE_HIDDEN_1
WEIGHT_MAX_HIDDEN_2    = INPUT_SCALE / WEIGHT_SCALE_HIDDEN_2
WEIGHT_MAX_OUT         = INPUT_SCALE / WEIGHT_SCALE_OUT

WEIGHT_MIN_HIDDEN_1    = -WEIGHT_MAX_HIDDEN_1
WEIGHT_MIN_HIDDEN_2    = -WEIGHT_MAX_HIDDEN_2
WEIGHT_MIN_OUT         = -WEIGHT_MAX_OUT

OUTPUT_SCALE = 301
